Inference:
  postprocess:
    args:
      module_name: MycaPostProcessor
      python_file: config/custom.py
    type: CustomProcessor
  preprocess:
    args:
      module_name: MycaPreProcessor
      python_file: config/custom.py
    type: CustomProcessor
  weights: ""

Model:
  args:
    module_name: MycaParentRecommendationModel
    python_file: config/custom.py
  type: CustomModel

Trainer:
  dataloader:
    args:
      batch_size: 64
      data_dir: data/
      module_name: MycaDataset
      num_workers: 1
      python_file: config/custom.py
      shuffle: true
      validation_split: 0.2
    type: CustomDataLoader
  loss: nll_loss
  lr_scheduler:
    args:
      gamma: 0.1
      step_size: 50
    type: StepLR
  metrics:
    - accuracy
    - top_k_acc
  n_gpu: 1
  name: MycaParentRecommendationTrainer
  optimizer:
    args:
      amsgrad: true
      lr: 0.001
      weight_decay: 0
    type: Adam
  trainer:
    early_stop: 10
    epochs: 3
    monitor: min val_loss
    save_dir: output/
    save_period: 1
    tensorboard: true
    verbosity: 2
