Inference:
  postprocess:
    args:
      module_name: MycaPostProcessor
      python_file: config/custom.py
    type: CustomProcessor
  preprocess:
    args:
      module_name: MycaPreProcessor
      python_file: config/custom.py
    type: CustomProcessor
  weights: ''
Logger:
  disable_existing_loggers: false
  formatters:
    datetime:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    simple:
      format: '%(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
    info_file_handler:
      backupCount: 20
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: info.log
      formatter: datetime
      level: INFO
      maxBytes: 10485760
  log_dir: logs/
  root:
    handlers:
    - console
    - info_file_handler
    level: INFO
  version: 1
Model:
  args:
    batch_first: true
    embedding_length: 512
    module_name: MycaParentModel
    ph_ff_dim: 512
    ph_nhead: 8
    ph_nlayers: 1
    python_file: config/custom.py
  type: CustomModel
Trainer:
  dataloader:
    args:
      batch_size: 64
      data_dir: data/user_2_dataset.csv
      module_name: MycaDataset
      num_workers: 1
      python_file: config/custom.py
      shuffle: true
      validation_split: 0.2
    type: CustomDataLoader
  loss: mse_loss
  lr_scheduler:
    args:
      gamma: 0.1
      step_size: 50
    type: StepLR
  metrics:
  - mse
  n_gpu: 1
  name: MycaParentTrainer
  optimizer:
    args:
      amsgrad: true
      lr: 0.001
      weight_decay: 0
    type: Adam
  trainer:
    early_stop: 10
    epochs: 20
    monitor: min val_loss
    save_dir: output/
    save_period: 1
    tensorboard: true
    verbosity: 2
